services:
  - type: web
    name: arch-circare-api
    env: python
    rootDir: navigator
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: starter
    envVars:
      - key: DATA_DIR
        value: ../data
      - key: MAX_UPLOAD_MB
        value: "10"
      - key: ALLOW_PDF
        value: "true"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: UPLOAD_TMP_DIR
        value: /tmp

staticSites:
  - name: arch-circare-ui
    rootDir: ui
    buildCommand: npm ci --no-audit --no-fund && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: arch-circare-api
          property: url
