services:
  - type: web
    name: arch-circare-api
    runtime: python
    rootDir: navigator
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: starter
    envVars:
      - key: DATA_DIR
        value: ../data
      - key: MAX_UPLOAD_MB
        value: "10"
      - key: ALLOW_PDF
        value: "true"
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: arch-circare-ui
          property: url
      - key: UPLOAD_TMP_DIR
        value: /tmp

  - type: web
    name: arch-circare-ui
    runtime: static
    rootDir: ui
    buildCommand: npm ci --no-audit --no-fund && npm run build
    startCommand: npx serve -s dist -l $PORT
    plan: starter
    envVars:
      - key: VITE_API_BASE_URL
        value: https://arch-circare-api.onrender.com